In [1]:
import pandas as pd

In [2]:
#check pandas version
print(pd.__version__)

1.4.2

# Series create

In [3]:
# creating a series from a list
arr=[0,1,2,3,4]
s1=pd.Series(arr)
s1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [4]:
order=[1,2,3,4,5]
s2=pd.Series(arr,index=order)
s2

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [5]:
order=['A','B','C','D','E'] #Using characters
s3=pd.Series(arr,index=order)
s3

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [6]:
import numpy as np
n=np.random.randn(5)#create a random ndarray
n

array([-0.21835583,  0.15693644,  1.47268496,  1.83794801, -0.65910194])

In [8]:
#create series from numpy library
import numpy as np
n=np.random.randn(5)#create a random ndarray
order=['A','B','C','D','E']
s3=pd.Series(n,index=order)
s3

A    1.134300
B   -1.719177
C    1.343079
D   -0.353624
E    0.545638
dtype: float64

In [9]:
#create series from dictionary
d={'A':1,'B':2,'C':3,'D':4,'E':5}
print(pd.Series(d))

A    1
B    2
C    3
D    4
E    5
dtype: int64

# Modify series

In [10]:
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [13]:
s1.index=['A','B','C','D','E']
s1

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [14]:
#Slicing
a=s1[:3]
a

A    0
B    1
C    2
dtype: int64

In [15]:
s1[3:]

D    3
E    4
dtype: int64

In [16]:
s1

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [17]:
s2

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [19]:
s4=s1.append(s2)
s4

C:\Users\DELL\AppData\Local\Temp\ipykernel_14280\2562205657.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s4=s1.append(s2)

A    0
B    1
C    2
D    3
E    4
1    0
2    1
3    2
4    3
5    4
dtype: int64

In [20]:
s4.drop(1)

A    0
B    1
C    2
D    3
E    4
2    1
3    2
4    3
5    4
dtype: int64

In [21]:
s3

A    1.134300
B   -1.719177
C    1.343079
D   -0.353624
E    0.545638
dtype: float64

In [22]:
s4

A    0
B    1
C    2
D    3
E    4
1    0
2    1
3    2
4    3
5    4
dtype: int64

# Series Operations

In [23]:
arr1=[0,1,2,3,4,5,7]
arr2=[6,7,8,9,5]

In [24]:
s5=pd.Series(arr2)
s5

0    6
1    7
2    8
3    9
4    5
dtype: int64

In [25]:
s6=pd.Series(arr1)
s6

0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64

In [26]:
s5.add(s6)

0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
dtype: float64

In [27]:
s5.sub(s6)

0    6.0
1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    NaN
dtype: float64

In [28]:
s5.mul(s6)

0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
dtype: float64

In [29]:
s5.div(s6)

0     inf
1    7.00
2    4.00
3    3.00
4    1.25
5     NaN
6     NaN
dtype: float64

In [32]:
print('Median',s6.median())
print('Max',s6.max())
print('Min',s6.min())

Median 3.0
Max 7
Min 0

# Dataframe create

In [46]:
#Creating datafram
data1=[1,2,3,4,'Pranali']
df=pd.DataFrame(data1)
df

         0
0        1
1        2
2        3
3        4
4  Pranali

In [47]:
data1=[1,2,3,4,'Pranali']
order=['A','B','C','D','E']
order1=['A']
df=pd.DataFrame(data1,index=order,columns=order1)
df

         A
A        1
B        2
C        3
D        4
E  Pranali

In [5]:
import pandas as pd
import numpy as np
dates=pd.date_range('today',periods=6) #Define time sequence as index
num_array=np.random.randn(6,4) #import numpy random array
order=['A','B','C','D'] #Use the table as the column name
df=pd.DataFrame(num_array,index=dates,columns=order)
df

                                   A         B         C         D
2023-02-14 14:29:07.415354  0.301564  1.274495  0.556447 -0.887339
2023-02-15 14:29:07.415354 -0.180944  1.242059  1.372045 -1.069553
2023-02-16 14:29:07.415354  0.799387  0.388254 -0.440440 -0.837883
2023-02-17 14:29:07.415354 -1.367653  1.654083  0.865762  0.940331
2023-02-18 14:29:07.415354 -1.618279  0.231959 -1.208160  0.479721
2023-02-19 14:29:07.415354 -0.040769 -0.105943 -0.674856 -0.227760

In [10]:
data={'Name':['Shahu','Om','Shambhu','Pranali','Radha','Swara'],'Age':[7,6,3,20,17,22],'Education':['5th standard','4th standard','Nursery','Graduation','HSC','Under Graduate']}
order=['A','B','C','D','E','F']
df1=pd.DataFrame(data,index=order)
df1

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [11]:
# Define datatypes of array
df1.dtypes

Name         object
Age           int64
Education    object
dtype: object

In [12]:
# Show first five values
df1.head()

      Name  Age     Education
A    Shahu    7  5th standard
B       Om    6  4th standard
C  Shambhu    3       Nursery
D  Pranali   20    Graduation
E    Radha   17           HSC

In [13]:
# Show first two values
df1.head(2)

    Name  Age     Education
A  Shahu    7  5th standard
B     Om    6  4th standard

In [14]:
# Show first six values
df1.head(6)

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [16]:
# show last five values
df1.tail()

      Name  Age       Education
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [17]:
# show last three values
df1.tail(3)

      Name  Age       Education
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [19]:
# show index names
df1.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [20]:
# show column names
df1.columns

Index(['Name', 'Age', 'Education'], dtype='object')

In [21]:
# show all the values in an array 
df1.values

array([['Shahu', 7, '5th standard'],
       ['Om', 6, '4th standard'],
       ['Shambhu', 3, 'Nursery'],
       ['Pranali', 20, 'Graduation'],
       ['Radha', 17, 'HSC'],
       ['Swara', 22, 'Under Graduate']], dtype=object)

In [22]:
# show statistical data of dataframe
df1.describe()

             Age
count   6.000000
mean   12.500000
std     8.117881
min     3.000000
25%     6.250000
50%    12.000000
75%    19.250000
max    22.000000

In [23]:
# Replace the columnn values with index values
df1.T

,A,B,C,D,E,F
Name,Shahu,Om,Shambhu,Pranali,Radha,Swara
Age,7,6,3,20,17,22
Education,5th standard,4th standard,Nursery,Graduation,HSC,Under Graduate

In [24]:
# Sorting in ascending order
df1.sort_values(by='Age')

      Name  Age       Education
C  Shambhu    3         Nursery
B       Om    6    4th standard
A    Shahu    7    5th standard
E    Radha   17             HSC
D  Pranali   20      Graduation
F    Swara   22  Under Graduate

In [27]:
df1.sort_values(by='Name')

      Name  Age       Education
B       Om    6    4th standard
D  Pranali   20      Graduation
E    Radha   17             HSC
A    Shahu    7    5th standard
C  Shambhu    3         Nursery
F    Swara   22  Under Graduate

In [28]:
#Slicing dataframe
df1[1:3]

      Name  Age     Education
B       Om    6  4th standard
C  Shambhu    3       Nursery

In [29]:
#Slicing dataframe
df1[:3]

      Name  Age     Education
A    Shahu    7  5th standard
B       Om    6  4th standard
C  Shambhu    3       Nursery

In [30]:
#Slicing dataframe
df1[2:]

      Name  Age       Education
C  Shambhu    3         Nursery
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [31]:
#Sorting in slicing dataframe
df1.sort_values(by='Age')[1:4]

    Name  Age     Education
B     Om    6  4th standard
A  Shahu    7  5th standard
E  Radha   17           HSC

In [38]:
df1[['Name','Age']]

      Name  Age
A    Shahu    7
B       Om    6
C  Shambhu    3
D  Pranali   20
E    Radha   17
F    Swara   22

In [39]:
#Copy dataframe in another dataframe
df2=df1.copy()
df2

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   20      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [40]:
df2.isnull()

    Name    Age  Education
A  False  False      False
B  False  False      False
C  False  False      False
D  False  False      False
E  False  False      False
F  False  False      False

In [42]:
#Change the existed value
df1.loc['D','Age']=21
df1

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   21      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [43]:
#Find mean value
df1.mean()

C:\Users\DELL\AppData\Local\Temp\ipykernel_18152\2053335143.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1.mean()

Age    12.666667
dtype: float64

In [44]:
#Find summation
df1['Age'].sum()

76

In [45]:
#Find mean value for particular column
df1['Age'].mean()

12.666666666666666

In [48]:
#Find minimum value
df1['Age'].min()

3

In [49]:
#Find maximum value
df1['Age'].max()

22

In [50]:
df1.sum()

Name                           ShahuOmShambhuPranaliRadhaSwara
Age                                                         76
Education    5th standard4th standardNurseryGraduationHSCUn...
dtype: object

# Operations for Dataframe missing values

In [51]:
df3=df1.copy()
df3

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   21      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

In [56]:
df3=df1.copy()
df3.fillna(3)
df3

      Name  Age       Education
A    Shahu    7    5th standard
B       Om    6    4th standard
C  Shambhu    3         Nursery
D  Pranali   21      Graduation
E    Radha   17             HSC
F    Swara   22  Under Graduate

# Pandas new code

In [1]:
import pandas as pd

# Read CSV file

In [8]:
df=pd.read_csv("E:\SQL Practice\Sample.csv")

In [9]:
df

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT
9      10   Pranali    Walve   22   20000    Computer

# Show Top 5 values

In [10]:
df.head()

   rollno    fname    lname  age  salary        dept
0       1       Om    Barde    8    2000    Computer
1       2  Shambhu    Barde    6    4000          IT
2       3    Shahu  Medhane    9    6000    Computer
3       4     Amit    Nigal   25    8000  Electrical
4       5    Sumit    Nigal   27   10000  Mechanical

# Show Bottom 5 values

In [11]:
df.tail()

   rollno     fname  lname  age  salary      dept
5       6  Prashant  Walve   25   12000        IT
6       7    Sandip  Nigal   32   14000  Computer
7       8    Kaveri  Nigal   16   16000     Civil
8       9    Yogesh  Barde   35   18000        IT
9      10   Pranali  Walve   22   20000  Computer

# Check Datatype

In [12]:
df.dtypes

rollno     int64
fname     object
lname     object
age        int64
salary     int64
dept      object
dtype: object

# Calculate using Describe

In [13]:
df.describe()

         rollno       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  20.50000  11000.000000
std     3.02765  10.25508   6055.300708
min     1.00000   6.00000   2000.000000
25%     3.25000  10.75000   6500.000000
50%     5.50000  23.50000  11000.000000
75%     7.75000  26.50000  15500.000000
max    10.00000  35.00000  20000.000000

In [15]:
df[["fname","lname"]]

      fname    lname
0        Om    Barde
1   Shambhu    Barde
2     Shahu  Medhane
3      Amit    Nigal
4     Sumit    Nigal
5  Prashant    Walve
6    Sandip    Nigal
7    Kaveri    Nigal
8    Yogesh    Barde
9   Pranali    Walve

In [16]:
df.dtypes == 'object'

rollno    False
fname      True
lname      True
age       False
salary    False
dept       True
dtype: bool

In [17]:
df.dtypes == 'float64'

rollno    False
fname     False
lname     False
age       False
salary    False
dept      False
dtype: bool

In [20]:
df.dtypes == 'int64'

rollno     True
fname     False
lname     False
age        True
salary     True
dept      False
dtype: bool

In [21]:
df[df.dtypes[df.dtypes == 'int64'].index]

   rollno  age  salary
0       1    8    2000
1       2    6    4000
2       3    9    6000
3       4   25    8000
4       5   27   10000
5       6   25   12000
6       7   32   14000
7       8   16   16000
8       9   35   18000
9      10   22   20000

In [22]:
df.head(3)

   rollno    fname    lname  age  salary      dept
0       1       Om    Barde    8    2000  Computer
1       2  Shambhu    Barde    6    4000        IT
2       3    Shahu  Medhane    9    6000  Computer

In [23]:
df.tail(3)

   rollno    fname  lname  age  salary      dept
7       8   Kaveri  Nigal   16   16000     Civil
8       9   Yogesh  Barde   35   18000        IT
9      10  Pranali  Walve   22   20000  Computer

In [25]:
# Show Column names
df.columns

Index(['rollno', 'fname', 'lname', 'age', 'salary', 'dept'], dtype='object')

# slicing

In [26]:
df[['fname']][1:4]

     fname
1  Shambhu
2    Shahu
3     Amit

In [27]:
df[['fname','lname']][1:4]

     fname    lname
1  Shambhu    Barde
2    Shahu  Medhane
3     Amit    Nigal

In [28]:
df[['fname','lname']][1:8:3] #Print 1 to 8 step by 2

     fname  lname
1  Shambhu  Barde
4    Sumit  Nigal
7   Kaveri  Nigal

# Add new column

In [29]:
df['new_col'] = 0

In [30]:
df

   rollno     fname    lname  age  salary        dept  new_col
0       1        Om    Barde    8    2000    Computer        0
1       2   Shambhu    Barde    6    4000          IT        0
2       3     Shahu  Medhane    9    6000    Computer        0
3       4      Amit    Nigal   25    8000  Electrical        0
4       5     Sumit    Nigal   27   10000  Mechanical        0
5       6  Prashant    Walve   25   12000          IT        0
6       7    Sandip    Nigal   32   14000    Computer        0
7       8    Kaveri    Nigal   16   16000       Civil        0
8       9    Yogesh    Barde   35   18000          IT        0
9      10   Pranali    Walve   22   20000    Computer        0

In [31]:
df['Pranali'] = 5

In [32]:
df

   rollno     fname    lname  age  salary        dept  new_col  Pranali
0       1        Om    Barde    8    2000    Computer        0        5
1       2   Shambhu    Barde    6    4000          IT        0        5
2       3     Shahu  Medhane    9    6000    Computer        0        5
3       4      Amit    Nigal   25    8000  Electrical        0        5
4       5     Sumit    Nigal   27   10000  Mechanical        0        5
5       6  Prashant    Walve   25   12000          IT        0        5
6       7    Sandip    Nigal   32   14000    Computer        0        5
7       8    Kaveri    Nigal   16   16000       Civil        0        5
8       9    Yogesh    Barde   35   18000          IT        0        5
9      10   Pranali    Walve   22   20000    Computer        0        5

# Add column which u want

In [34]:
df.insert(loc=3, column='abc', value=0)

In [35]:
df

   rollno     fname    lname  abc  age  salary        dept  new_col  Pranali
0       1        Om    Barde    0    8    2000    Computer        0        5
1       2   Shambhu    Barde    0    6    4000          IT        0        5
2       3     Shahu  Medhane    0    9    6000    Computer        0        5
3       4      Amit    Nigal    0   25    8000  Electrical        0        5
4       5     Sumit    Nigal    0   27   10000  Mechanical        0        5
5       6  Prashant    Walve    0   25   12000          IT        0        5
6       7    Sandip    Nigal    0   32   14000    Computer        0        5
7       8    Kaveri    Nigal    0   16   16000       Civil        0        5
8       9    Yogesh    Barde    0   35   18000          IT        0        5
9      10   Pranali    Walve    0   22   20000    Computer        0        5

In [36]:
df.insert(loc=4, column='Brand', value='Pranali Valve')

In [37]:
df

,rollno,fname,lname,abc,Brand,age,salary,dept,new_col,Pranali
0,1,Om,Barde,0,Pranali Valve,8,2000,Computer,0,5
1,2,Shambhu,Barde,0,Pranali Valve,6,4000,IT,0,5
2,3,Shahu,Medhane,0,Pranali Valve,9,6000,Computer,0,5
3,4,Amit,Nigal,0,Pranali Valve,25,8000,Electrical,0,5
4,5,Sumit,Nigal,0,Pranali Valve,27,10000,Mechanical,0,5
5,6,Prashant,Walve,0,Pranali Valve,25,12000,IT,0,5
6,7,Sandip,Nigal,0,Pranali Valve,32,14000,Computer,0,5
7,8,Kaveri,Nigal,0,Pranali Valve,16,16000,Civil,0,5
8,9,Yogesh,Barde,0,Pranali Valve,35,18000,IT,0,5
9,10,Pranali,Walve,0,Pranali Valve,22,20000,Computer,0,5

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("E:\SQL Practice\Sample.csv")

In [4]:
df

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT
9      10   Pranali    Walve   22   20000    Computer

# Slicing

In [9]:
a = df['fname'][0:5]

In [10]:
a

0         Om
1    Shambhu
2      Shahu
3       Amit
4      Sumit
Name: fname, dtype: object

In [11]:
type(a)

pandas.core.series.Series

In [2]:
import pandas as pd

In [3]:
a=df=pd.read_csv("E:\SQL Practice\Sample.csv")

In [4]:
a

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT
9      10   Pranali    Walve   22   20000    Computer

In [16]:
l = ['a','b','c','d','e','f','g','h','i','j']
pd.Series(a, index = l)

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
h    NaN
i    NaN
j    NaN
Name: fname, dtype: object

In [14]:
a = df['fname'][0:5]

In [15]:
a

0         Om
1    Shambhu
2      Shahu
3       Amit
4      Sumit
Name: fname, dtype: object

In [18]:
l1 = ['a','b','c','d','e']
pd.Series(a, index = l1)

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
Name: fname, dtype: object

# Remove NaN using list()

In [20]:
l1 = ['a','b','c','d','e']
pd.Series(list(a), index = l1)

a         Om
b    Shambhu
c      Shahu
d       Amit
e      Sumit
dtype: object

In [29]:
m1 = pd.Series([10,20,30,40,50],index = [1,2,3,4,5])

In [30]:
m1

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [31]:
m2 = pd.Series([100,200,300,400,500],index = [1,2,3,4,5])

In [32]:
m2

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [33]:
m3 = pd.concat([m1,m2])

In [34]:
m3

1     10
2     20
3     30
4     40
5     50
1    100
2    200
3    300
4    400
5    500
dtype: int64

In [35]:
m3[1]

1     10
1    100
dtype: int64

In [36]:
m1*m2

1     1000
2     4000
3     9000
4    16000
5    25000
dtype: int64

In [37]:
m1+m2

1    110
2    220
3    330
4    440
5    550
dtype: int64

In [38]:
df

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT
9      10   Pranali    Walve   22   20000    Computer

# Delete Column

delete temporary

In [7]:
# Delete Temporary
df.drop("age", axis = 1)

   rollno     fname    lname  salary        dept
0       1        Om    Barde    2000    Computer
1       2   Shambhu    Barde    4000          IT
2       3     Shahu  Medhane    6000    Computer
3       4      Amit    Nigal    8000  Electrical
4       5     Sumit    Nigal   10000  Mechanical
5       6  Prashant    Walve   12000          IT
6       7    Sandip    Nigal   14000    Computer
7       8    Kaveri    Nigal   16000       Civil
8       9    Yogesh    Barde   18000          IT
9      10   Pranali    Walve   20000    Computer

Delete Permanent

In [41]:
df.drop("age", axis = 1, inplace = True)

In [42]:
df

   rollno     fname    lname  salary        dept
0       1        Om    Barde    2000    Computer
1       2   Shambhu    Barde    4000          IT
2       3     Shahu  Medhane    6000    Computer
3       4      Amit    Nigal    8000  Electrical
4       5     Sumit    Nigal   10000  Mechanical
5       6  Prashant    Walve   12000          IT
6       7    Sandip    Nigal   14000    Computer
7       8    Kaveri    Nigal   16000       Civil
8       9    Yogesh    Barde   18000          IT
9      10   Pranali    Walve   20000    Computer

In [43]:
df=pd.read_csv("E:\SQL Practice\Sample.csv")

In [44]:
df

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT
9      10   Pranali    Walve   22   20000    Computer

In [45]:
df.drop(9)

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT

In [46]:
df.drop(9, inplace = True)

In [47]:
df

   rollno     fname    lname  age  salary        dept
0       1        Om    Barde    8    2000    Computer
1       2   Shambhu    Barde    6    4000          IT
2       3     Shahu  Medhane    9    6000    Computer
3       4      Amit    Nigal   25    8000  Electrical
4       5     Sumit    Nigal   27   10000  Mechanical
5       6  Prashant    Walve   25   12000          IT
6       7    Sandip    Nigal   32   14000    Computer
7       8    Kaveri    Nigal   16   16000       Civil
8       9    Yogesh    Barde   35   18000          IT

# Particular column convert to index

In [48]:
df.set_index('dept')

            rollno     fname    lname  age  salary
dept
Computer         1        Om    Barde    8    2000
IT               2   Shambhu    Barde    6    4000
Computer         3     Shahu  Medhane    9    6000
Electrical       4      Amit    Nigal   25    8000
Mechanical       5     Sumit    Nigal   27   10000
IT               6  Prashant    Walve   25   12000
Computer         7    Sandip    Nigal   32   14000
Civil            8    Kaveri    Nigal   16   16000
IT               9    Yogesh    Barde   35   18000

In [49]:
df.set_index('dept', inplace = True)

In [50]:
df

            rollno     fname    lname  age  salary
dept
Computer         1        Om    Barde    8    2000
IT               2   Shambhu    Barde    6    4000
Computer         3     Shahu  Medhane    9    6000
Electrical       4      Amit    Nigal   25    8000
Mechanical       5     Sumit    Nigal   27   10000
IT               6  Prashant    Walve   25   12000
Computer         7    Sandip    Nigal   32   14000
Civil            8    Kaveri    Nigal   16   16000
IT               9    Yogesh    Barde   35   18000

In [51]:
df.reset_index()

         dept  rollno     fname    lname  age  salary
0    Computer       1        Om    Barde    8    2000
1          IT       2   Shambhu    Barde    6    4000
2    Computer       3     Shahu  Medhane    9    6000
3  Electrical       4      Amit    Nigal   25    8000
4  Mechanical       5     Sumit    Nigal   27   10000
5          IT       6  Prashant    Walve   25   12000
6    Computer       7    Sandip    Nigal   32   14000
7       Civil       8    Kaveri    Nigal   16   16000
8          IT       9    Yogesh    Barde   35   18000

# Making dataframe from the dictionary

In [53]:
d = {"key1" :[1,2,3],
     "key2" :[4,5,6],
     "key3" :[7,8,9]
    }

In [54]:
d

{'key1': [1, 2, 3], 'key2': [4, 5, 6], 'key3': [7, 8, 9]}

In [55]:
pd.DataFrame(d)

   key1  key2  key3
0     1     4     7
1     2     5     8
2     3     6     9